### ISSUE TITLE
Development Goals - Week 2 

### ISSUE THREAD

**Issue by NaomiOkiddy** [SWE2-2020-8/NewBank#15]
- [x] #10  Get the server running so we can make  @gabrielbcn 
- [x] #11 Get the sockets up and running - read up on java socket programming @gabrielbcn 
- [ ] #12 Implement functionality for NEWACCOUNT, MOVE and PAY in the server and rework SHOWMYACCOUNTS @saraalkuwari1 
- [ ] #13 Implement functionality in the client: option-based interaction @sj702 
- [ ] #14 Implement User authentication both in the client and in the server @NaomiOkiddy 
- [x]  #18 Provide persistent storage in the server (backlog) @gabrielbcn 

Backlog can be found on the [wiki](https://github.com/SWE2-2020-8/NewBank.wiki.git)

**Comment by gabrielbcn** [comment]
Corrected link to wiki

https://github.com/SWE2-2020-8/NewBank/wiki

**Comment by NaomiOkiddy** [comment]
Please answer all these questions as comments in this issue.
1. What have I done this week?
2. What problems have I encountered?
3. Have I solved them and how?

**Comment by NaomiOkiddy** [comment]
Unfinished goals for this week will be moved to next week's sprint.
