### ISSUE TITLE
Development Goals - Week 3

### ISSUE THREAD

**Issue by saraalkuwari1** [SWE2-2020-8/NewBank#20]
- [x] Server to store information on database - persistent storage to be #21 

- [x] Implement an Admin user to create new users and validate new  #22 

- [x] Allow users to change their passwords #23

**Comment by NaomiOkiddy** [comment]
Done!
