### ISSUE TITLE
Development Goals Week 4

### ISSUE THREAD

**Issue by NaomiOkiddy** [SWE2-2020-8/NewBank#35]
- [ ] Implement functionality for NEWACCOUNT, MOVE and PAY in the server and rework SHOWMYACCOUNTS @saraalkuwari1 #12 
- [ ] Implement functionalists in client   #34 @gabrielbcn
- [ ] Implement loaning services #36 @NaomiOkiddy 
- [ ] Implement interest accrual functionality #37
- [ ] Request portal as in request check book, new card #38 @NaomiOkiddy

**Comment by gabrielbcn** [comment]
Sorry was trying to close the client not this one

**Comment by gabrielbcn** [comment]
Updated in wiki
