### ISSUE TITLE
Development Goals - Week 5

### ISSUE THREAD

**Issue by saraalkuwari1** [SWE2-2020-8/NewBank#49]
- [x] Automation of client build using container  #44 @gabrielbcn 

- [x] Software release to allow download versions #45 @gabrielbcn 

- [x]  Create newbankclient.jar as artefact of the action #46 @gabrielbcn 

- [x] Create newbankclient.jar as artefact included in releases #47  @gabrielbcn 

- [x] Server to comply requirements when logging in #51 

- [x] Server to comply requirements when writing comments or printing the option #52 @NaomiOkiddy 

- [x]  Server to check compliant #53 @NaomiOkiddy 

- [x] Server to allow for Withdrawals #54 @saraalkuwari1 

- [x] Client should support #55 @NaomiOkiddy

**Comment by gabrielbcn** [comment]
At this time, only pending seems to be PAY @saraalkuwari1 @NaomiOkiddy

**Comment by gabrielbcn** [comment]
All done. Password complexity left inactive for practical reasons.
